<div class="btn-group" style="margin-bottom: 10px">
    <a href="<?= U('Home/Upload/upload') ?>" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> 销售记录上传</a>
</div>
<table class="table table-bordered">
    <tr>
        <td class="col-md-1">记录ID</td>
        <td class="col-md-3">店铺名称</td>
        <td class="col-md-2">文件名</td>
        <td class="col-md-1">执行状态</td>
        <td class="col-md-2">创建时间</td>
        <td class="col-md-3">操作</td>
    </tr>
    <?php foreach ($list as $v) { ?>
        <tr>
            <td><?= $v['id'] ?></td>
            <td><?= $v['platform_name'] ?></td>
            <td><?= $v['file_name'] ?></td>
            <td class="<?= $v['status'] == 1 ? 'bg-success' : ($v['status'] == 2 ? 'bg-danger' : 'bg-info') ?>">
                <?php if ($v['status'] == 1) { ?>
                    已完成
                <?php } else if ($v['status'] == 0) { ?>
                    未执行
                <?php } else { ?>
                    同步错误
                <?php } ?>
            </td>
            <td><?= date('Y-m-d H:i:s', $v['create_time']) ?></td>
            <td>
                <?php if ($v['status'] == 0) { ?>
                    <a onClick="javascript:window.open('<?= U('Home/Upload/complete', ['id' => $v['id']]) ?>','','width=632,height=388,toolbar=no, status=no, menubar=no, resizable=yes, scrollbars=yes');return false;"
                       href="#" target="_blank" class="btn btn-sm btn-primary"><i
                                class="glyphicon glyphicon-refresh"></i> 立即同步</a>
                    <a href="<?= U('Home/Upload/delete', ['id' => $v['id']]) ?>"
                       class="btn btn-sm btn-default"><i class="glyphicon glyphicon-remove"></i> 删除</a>
                <?php } ?>
                <?php if ($v['status'] == 1) { ?>
                    <a onClick="javascript:window.open('<?= U('Home/Upload/seeLog', ['id' => $v['id']]) ?>','','width=632,height=388,toolbar=no, status=no, menubar=no, resizable=yes, scrollbars=yes');return false;"
                       href="#" target="_blank" class="btn btn-sm btn-warning"><i
                                class="glyphicon glyphicon-eye-open"></i> 查看日志</a>
                <?php } ?>
                <?php if ($v['wsdl_need'] && $v['status'] == 2) { ?>
                    <a href="<?= U('Home/Upload/wsdlList', ['id' => $v['id']]) ?>"
                       class="btn btn-sm btn-danger"><i
                                class="glyphicon glyphicon-eye-open"></i> 错误详情</a>
                    <a onClick="javascript:window.open('<?= U('Home/Upload/seeLog', ['id' => $v['id']]) ?>','','width=632,height=388,toolbar=no, status=no, menubar=no, resizable=yes, scrollbars=yes');return false;"
                       href="#" target="_blank" class="btn btn-sm btn-warning"><i
                                class="glyphicon glyphicon-eye-open"></i> 查看日志</a>
                <?php } else if ($v['ftp_need'] && $v['status'] == 2) { ?>
                    <a onClick="javascript:window.open('<?= U('Home/Upload/seeLog', ['id' => $v['id']]) ?>','','width=632,height=388,toolbar=no, status=no, menubar=no, resizable=yes, scrollbars=yes');return false;"
                       href="#" target="_blank" class="btn btn-sm btn-danger"><i
                                class="glyphicon glyphicon-eye-open"></i> 错误详情</a>
                <?php } ?>
            </td>
        </tr>
    <?php } ?>

</table>

<?php if ($total_page > 1) { ?>
    <div style="text-align: center">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li <?= $current_page == 1 ? 'class="disabled"' : '' ?>>
                <a href="<?= U('Home/Upload/index', ['page' => $current_page == 1 ? $current_page : $current_page - 1]) ?>"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <?php if ($total_page <= 10) {
                $max = $total_page;
                $min = 1;
            } else if ($current_page + 5 <= $total_page && $current_page >= 5) {
                $max = $current_page + 5;
                $min = $current_page - 4;
            } else if ($current_page <= $total_page && $current_page + 5 >= $total_page) {
                $max = $total_page;
                $min = $total_page - 9;
            } else if ($current_page <= 5) {
                $min = 1;
                $max = 10;
            }
            for ($i = $min; $i <= $max; $i++) { ?>
                <li <?= $i == $current_page ? 'class="active"' : '' ?>><a
                            href="<?= U('Home/Upload/index', ['page' => $i]) ?>"><?= $i ?></a></li>
            <?php } ?>
            <li <?= $current_page == $total_page ? 'class="disabled"' : '' ?>>
                <a href="<?= U('Home/Upload/index', ['page' => $current_page == $total_page ? $current_page : $current_page + 1]) ?>"
                   aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
    </div>
<?php } ?>