<div class="container clearfix">
    <div class="col-sm-6">
        <form class="form-horizontal" method="post" action="<?= U('Home/Upload/upload') ?>"
              enctype="multipart/form-data">

            <?php if ($user['is_admin']) { ?>
                <div class="form-group">
                    <label class="col-sm-4 control-label">店铺</label>
                    <div class="col-sm-8">
                        <select name="platform_id" class="form-control">
                            <option value>--请选择--</option>
                            <?php foreach ($platformList as $key => $platform) { ?>
                                <option value="<?= $key ?>"><?= $platform ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
            <?php } ?>
            <div class="form-group">
                <label class="col-sm-4 control-label">销售数据</label>
                <div class="col-sm-8" style="padding-top: 7px">
                    <input type="file" name="file">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <input type="submit" class="btn btn-success" value="确认"/>
                </div>
            </div>
        </form>

    </div>
</div>

