<div class="container clearfix">
    <div class="col-sm-6">
        <form class="form-horizontal" method="post">
            <?php if ($platform['platform_id']) { ?>
                <input type="hidden" name="platform_id" value="<?= $platform['platform_id'] ?>">
            <?php } ?>
            <div class="form-group">
                <label class="col-sm-4 control-label">店铺名称</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="platform_name" placeholder="店铺名称"
                           value="<?= $platform['platform_name'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">店铺关键字</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="type_code" placeholder="店铺关键字"
                           value="<?= $platform['type_code'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">是否需要FTP上传</label>
                <div class="col-sm-8" style="padding-top: 7px">
                    <span style="margin-right: 20px">
                        <label><input type="radio" name="ftp_need"
                                      value="0" <?= $platform['ftp_need'] == '0' ? 'checked' : '' ?>> 否</label></span>
                    <span><label><input type="radio" name="ftp_need"
                                        value="1" <?= $platform['ftp_need'] == '1' ? 'checked' : '' ?>> 是</label></span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">是否需要对接wsdl</label>
                <div class="col-sm-8" style="padding-top: 7px">
                    <span style="margin-right: 20px">
                        <label><input type="radio" name="wsdl_need"
                                      value="0" <?= $platform['wsdl_need'] == '0' ? 'checked' : '' ?>> 否</label></span>
                    <span><label><input type="radio" name="wsdl_need"
                                        value="1" <?= $platform['wsdl_need'] == '1' ? 'checked' : '' ?>> 是</label></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <input type="submit" class="btn btn-success" value="确认"/>
                </div>
            </div>
        </form>

    </div>
</div>

