<div class="container clearfix">
    <div class="col-sm-6">
        <form class="form-horizontal" method="post">
            <input type="hidden" name="platform_id" value="<?= $platform['platform_id'] ?>">
            <?php if ($ftp['conf_id']) { ?>
                <input type="hidden" name="conf_id" value="<?= $ftp['conf_id'] ?>">
            <?php } ?>
            <div class="form-group">
                <label class="col-sm-4 control-label">AR</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="ar" placeholder="ar"
                           value="<?= $ftp['ar'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">收银机编号</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="tillid" placeholder="收银机编号"
                           value="<?= $ftp['tillid'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">FTP地址</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="host" placeholder="FTP地址"
                           value="<?= $ftp['host'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">FTP端口</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="port" placeholder="FTP端口"
                           value="<?= $ftp['port'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">FTP用户名</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="username" placeholder="FTP用户名"
                           value="<?= $ftp['username'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">FTP连接密码</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="password" placeholder="FTP连接密码"
                           value="<?= $ftp['password'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">FTP文件名规则</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="file_name" placeholder="FTP文件名规则"
                           value="<?= $ftp['file_name'] ?>">
                </div>

            </div>
            <div class="form-group">
                <label class="col-sm-4 control-label">FTP内容规则</label>
                <div class="col-sm-8">
                    <textarea name="field_list" class="form-control" cols="30"
                              rows="5"><?= $ftp['field_list'] ?></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <input type="submit" class="btn btn-success" value="确认"/>
                </div>
            </div>
        </form>

    </div>
</div>

