<a href="<?= U('Home/User/add') ?>" class="btn btn-success">新增用户</a>
<!-- Large modal -->
<button type="button" class="btn btn-danger change-password-btn">修改密码</button>

<div style="padding: 10px">
    <form class="form-inline">
        <div class="form-group">
            <label for="exampleInputName2">用户名称</label>
            <input type="text" class="form-control" name="username" value="<?= $search['username'] ?>">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail2">店铺名称</label>
            <select class="form-control" name="platform_id">
                <option value="">--请选择--</option>
                <?php foreach ($platformList as $key => $value) { ?>
                    <option value="<?= $key ?>" <?= $search['platform_id'] == $key ? 'selected' : '' ?>><?= $value ?></option>
                <?php } ?>
            </select>
        </div>
        <input class="btn btn-primary" type="submit" value="搜索">

    </form>

</div>
<table class="table table-bordered user-list">
    <tr>
        <td class="col-md-1 " style="text-align: center"></td>
        <td class="col-md-1">用户编号</td>
        <td class="col-md-2">用户名称</td>
        <td class="col-md-2">店铺名称</td>
        <td class="col-md-1">用户状态</td>
        <td class="col-md-2">创建时间</td>
        <td class="col-md-3">操作</td>

    </tr>
    <?php foreach ($userList as $user) { ?>
        <tr>
            <td><input type="checkbox" name="user_id" value="<?= $user['user_id'] ?>"></td>
            <td><?= $user['user_id'] ?></td>
            <td><?= $user['username'] ?></td>
            <td><?= $platformList[$user['platform_id']] ?></td>
            <td><?= $user['status'] ? '使用中' : '已冻结' ?></td>
            <td><?= date('Y-m-d H:i:s', $user['create_time']) ?></td>
            <td>
                <?php if ($user['status'] == 1) { ?>
                    <a class="btn btn-sm btn-info"
                       href="<?= U('Home/User/freeze', ['user_id' => $user['user_id']]) ?>">
                        <i class="glyphicon glyphicon-ban-circle"></i>冻结</a>
                <?php } ?>
                <?php if ($user['status'] == 0) { ?>
                    <a class="btn btn-sm btn-success"
                       href="<?= U('Home/User/unfreeze', ['user_id' => $user['user_id']]) ?>">
                        <i class="glyphicon glyphicon-fire"></i> 解冻</a>
                <?php } ?>
            </td>
        </tr>
    <?php } ?>
</table>

